JSON_MODELS={
"WEDDING_PLANNERS":"""
{
  "website":"",
  "instagram":"",
  "facebook":"",
  "google_business":"",
  "phone":"",
  "email":"",
  "price_range":"",
  "rating":"",
  "review_count":"",
  "planning_speciality":[],
  "wedding_types_covered":[],
  "services_offered":[],
  "destination_wedding_support":"",
  "decoration_styles":[],
  "cities_covered":[],
  "guest_hospitality_management":[],
  "entertainment_services":[],
  "sources":[],
  "address":""
}"""
}